Request for code review.
Rocio01/PositioningandFloatingElements pull request #4
Opened 2020-06-17 15:48 UTC by Rocio01

Clone of New York Times Magazine.

2020-06-17 19:33 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-17 19:51 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, great job with this project, we passed validator check, linter and we have a good README file :slightly_smiling_face: However, we need to make some changes in order to improve our code. Kindly check the comments below so we can get our project approved: :+1: 
- Let us add a project-specific description to our README file and our PR(Pull Request). For example; Embedding images, Working with forms (buttons in this case), Positioning elements with float, flex and grid, The box model
- ``` Footer ```, the footer should also have the fixed feature as implemented for the nav
![fp](https://user-images.githubusercontent.com/46388113/84942817-f5b32300-b0d2-11ea-92b3-a3ce3b232bf3.png)
- Pull Request should have a meaningful title and a short description. Kindly edit the PR and apply the changes

Kindly make these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-17 19:51 UTC, addod19 commented on index.html
> +    <div class="article">
Let us improve semantics by using ```<article>``` instead of ```<div class="article">```

2020-06-18 17:59 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Hands down this is one of the best projects I have ever seen 🙌👌. Great job team!

### We need to make some changes before we can move ahead.

- The subscribe and login buttons in the navbar must be exactly like the original.
### Clone

![Annotation 2020-06-18 232428](https://user-images.githubusercontent.com/57726348/85055565-5ddd3400-b1bb-11ea-8c0e-10bd280a865b.jpg)

### Original

![Annotation 2020-06-18 232408](https://user-images.githubusercontent.com/57726348/85055584-66ce0580-b1bb-11ea-9b0b-edf438c574cb.jpg)

- There are some CSS property issues in your project. Check the comments.

2020-06-18 18:03 UTC, tirthajyoti-ghosh commented on css/style.css
> +  border-color: 1px solid #000;
This is an invalid property. When you are declaring border-color property, only put the color values. If you want to use other border properties, use the short-hand `border` property.

2020-06-18 18:05 UTC, tirthajyoti-ghosh commented on css/style.css
> +  margin-right: 1px 0 0;
`margin-right` only accepts one value. Use short-hand `margin` property to specify values of margins for other sides.

2020-06-18 18:06 UTC, tirthajyoti-ghosh commented on css/style.css
> +  margin-inline-end: 0;
This property doesn't exist.

2020-06-18 18:08 UTC, tirthajyoti-ghosh commented on README.md
> +[Github Repository Link](https://github.com/Rocio01/PositioningandFloatingElements/tree/feature-branch)
Also, your README file doesn't contain a live demo link. Whether your project is approved or not you must put a live demo link. Update the live demo link every time you make any changes.

2020-06-18 18:09 UTC, tirthajyoti-ghosh reviewed
Take care of these invalid CSS properties. And don't forget to put the live demo link in your README.

Happy coding 👨‍💻

2020-06-18 20:06 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! Your project looks amazing! It is definitely very impressive 🌟🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

_P.S. Please check my comments for additional **optional** changes you may want to make before merging_ 😄 

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-06-18 20:08 UTC, BrittanyBlake commented on css/style.css
> +  line-height: 1rem !important;
### [OPTIONAL]

- Try not to use `!important` in your CSS. If you need to override a style, try to using selectors with a higher specificity.

2020-06-18 20:08 UTC, BrittanyBlake commented on css/style.css
> +  line-height: 1rem !important;
### [OPTIONAL]

- Try not to use `!important` in your CSS. If you need to override a style, try to using selectors with a higher specificity.

2020-06-18 20:14 UTC, merged